add_test( CsvManager.Field /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvManager.Field]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvManager.Field PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvManager.FieldErrors /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvManager.FieldErrors]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvManager.FieldErrors PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvManager.Row /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvManager.Row]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvManager.Row PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvManager.RowError /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvManager.RowError]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvManager.RowError PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvManager.getNextRow /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvManager.getNextRow]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvManager.getNextRow PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvManager.getNextError /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvManager.getNextError]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvManager.getNextError PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvManager.getRowsCount /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvManager.getRowsCount]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvManager.getRowsCount PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvManager.countRows /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvManager.countRows]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvManager.countRows PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvManager.saveReplacedreplaceRow /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvManager.saveReplacedreplaceRow]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvManager.saveReplacedreplaceRow PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvStatistics.Counter /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvStatistics.Counter]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvStatistics.Counter PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvStatistics.FieldStatistic /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvStatistics.FieldStatistic]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvStatistics.FieldStatistic PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( CsvStatistics.CsvStatistics /home/brunoaquino/repos/fix-csv-qt/build-rls-qt/test-fix-csv [==[--gtest_filter=CsvStatistics.CsvStatistics]==] --gtest_also_run_disabled_tests)
set_tests_properties( CsvStatistics.CsvStatistics PROPERTIES WORKING_DIRECTORY /home/brunoaquino/repos/fix-csv-qt/build-rls-qt SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( test-fix-csv_TESTS CsvManager.Field CsvManager.FieldErrors CsvManager.Row CsvManager.RowError CsvManager.getNextRow CsvManager.getNextError CsvManager.getRowsCount CsvManager.countRows CsvManager.saveReplacedreplaceRow CsvStatistics.Counter CsvStatistics.FieldStatistic CsvStatistics.CsvStatistics)
